//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace UPS.AddressValidation.DTO.CSZ.Response

{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AddressValidationResponse
    {

        private Response responseField;

        private AddressValidationResultType[] addressValidationResultField;

        /// <remarks/>
        public Response Response
        {
            get { return this.responseField; }
            set { this.responseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressValidationResult",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddressValidationResultType[] AddressValidationResult
        {
            get { return this.addressValidationResultField; }
            set { this.addressValidationResultField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Response
    {

        private TransactionReference transactionReferenceField;

        private string responseStatusCodeField;

        private string responseStatusDescriptionField;

        private Error[] errorField;

        /// <remarks/>
        public TransactionReference TransactionReference
        {
            get { return this.transactionReferenceField; }
            set { this.transactionReferenceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseStatusCode
        {
            get { return this.responseStatusCodeField; }
            set { this.responseStatusCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseStatusDescription
        {
            get { return this.responseStatusDescriptionField; }
            set { this.responseStatusDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error")]
        public Error[] Error
        {
            get { return this.errorField; }
            set { this.errorField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TransactionReference
    {

        private string customerContextField;

        private string xpciVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerContext
        {
            get { return this.customerContextField; }
            set { this.customerContextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XpciVersion
        {
            get { return this.xpciVersionField; }
            set { this.xpciVersionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressType
    {

        private string cityField;

        private string stateProvinceCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get { return this.cityField; }
            set { this.cityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateProvinceCode
        {
            get { return this.stateProvinceCodeField; }
            set { this.stateProvinceCodeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressValidationResultType
    {

        private string rankField;

        private string qualityField;

        private AddressType addressField;

        private string postalCodeLowEndField;

        private string postalCodeHighEndField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rank
        {
            get { return this.rankField; }
            set { this.rankField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Quality
        {
            get { return this.qualityField; }
            set { this.qualityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddressType Address
        {
            get { return this.addressField; }
            set { this.addressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCodeLowEnd
        {
            get { return this.postalCodeLowEndField; }
            set { this.postalCodeLowEndField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCodeHighEnd
        {
            get { return this.postalCodeHighEndField; }
            set { this.postalCodeHighEndField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Error
    {

        private string errorSeverityField;

        private string errorCodeField;

        private string errorDescriptionField;

        private string minimumRetrySecondsField;

        private ErrorLocation[] errorLocationField;

        private string[] errorDigestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorSeverity
        {
            get { return this.errorSeverityField; }
            set { this.errorSeverityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorCode
        {
            get { return this.errorCodeField; }
            set { this.errorCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorDescription
        {
            get { return this.errorDescriptionField; }
            set { this.errorDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimumRetrySeconds
        {
            get { return this.minimumRetrySecondsField; }
            set { this.minimumRetrySecondsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorLocation")]
        public ErrorLocation[] ErrorLocation
        {
            get { return this.errorLocationField; }
            set { this.errorLocationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorDigest", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)
        ]
        public string[] ErrorDigest
        {
            get { return this.errorDigestField; }
            set { this.errorDigestField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ErrorLocation
    {

        private string errorLocationElementNameField;

        private string errorLocationElementReferenceField;

        private string errorLocationAttributeNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorLocationElementName
        {
            get { return this.errorLocationElementNameField; }
            set { this.errorLocationElementNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorLocationElementReference
        {
            get { return this.errorLocationElementReferenceField; }
            set { this.errorLocationElementReferenceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorLocationAttributeName
        {
            get { return this.errorLocationAttributeNameField; }
            set { this.errorLocationAttributeNameField = value; }
        }
    }
}
